apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: somethings.example.nodeshift
spec:
  # our full resource name will be something.nodeshift/v1
  group: example.nodeshift
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: somethings
    singular: something
    kind: Something
