apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: members.example.nodeshift.com
spec:
  group: example.nodeshift.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  names:
    plural: members
    singular: member
    kind: Member
